### ISSUE TITLE
NestJS 7 + Azure Func 

### ISSUE THREAD

**Issue by kauandotnet** [nestjs/swagger#737] opened 2020-05-12 12:46 UTC
Infinity load.

GET http://localhost:7071/api/swagger-ui-init.js net::ERR_ABORTED 404 (Not Found)

main.azure.ts

 ```
...
 // SWAGGER CONFIGURATION
  const options = new DocumentBuilder()
    .setTitle('Test')
    .setDescription('API Documentation')
    .setVersion('1.0')
    .addBearerAuth()
    .build();

  // RUN SWAGER
  const document = SwaggerModule.createDocument(app, options);
  SwaggerModule.setup('api', app, document);
...
```

package.json

```
...
"@azure/functions": "^1.0.3",
"@nestjs/azure-func-http": "^0.5.0",
"@nestjs/swagger": "^4.5.5",
"swagger-ui-express": "^4.1.4",
...
```

**Comment by kamilmysliwiec** [comment] 2020-05-12 12:57
Would you like to create a PR for this issue?

**Comment by kauandotnet** [comment] 2020-05-12 12:58
@kamilmysliwiec Sure, ill update soon

**Comment by jacobdo2** [comment] 2020-05-22 11:47
How do you guys get swagger to run swagger on azure func at all? For me, it never registers the swagger route.

**Comment by jacobdo2** [comment] 2020-05-22 12:47
Any luck on updating this, having the same issue.

**Comment by kauandotnet** [comment] 2020-05-22 17:23
@jacobdo2 , im too busy now, can you provide a minimal repository? I can do it on monday...

**Comment by felipecassiors** [comment] 2020-06-01 01:17
Is there any workaround at the moment?

**Comment by felipecassiors** [comment] 2020-06-02 15:52
Repository for reproduction: https://github.com/felipecassiors/nestjs-swagger-azure-func

See it works with `nest start`
![cLdOLUPefb](https://user-images.githubusercontent.com/29582865/83541350-ec6d6800-a4cf-11ea-8756-1fe2384dceee.gif)

But not with `func host start`
![JOJ0ZdmSow](https://user-images.githubusercontent.com/29582865/83541316-e1b2d300-a4cf-11ea-8ada-7eadfad2239c.gif)

**Comment by kauandotnet** [comment] 2020-06-04 12:11
> Repository for reproduction: https://github.com/felipecassiors/nestjs-swagger-azure-func
> 
> And you can try it right now in Gitpod: https://gitpod.io/#https://github.com/felipecassiors/nestjs-swagger-azure-func
> 
> Just run:
> 
> ```shell
> npm install
> npm run azure:start
> ```
> 
> See it works with `nest start`
> ![cLdOLUPefb](https://user-images.githubusercontent.com/29582865/83541350-ec6d6800-a4cf-11ea-8756-1fe2384dceee.gif)
> 
> But not with `func host start`
> ![JOJ0ZdmSow](https://user-images.githubusercontent.com/29582865/83541316-e1b2d300-a4cf-11ea-8ada-7eadfad2239c.gif)

Thanks, @kamilmysliwiec can you check this?

**Comment by K1kk3rt** [comment] 2020-09-09 13:08
Any idea when this will be fixed? I saw a[ pull request](https://github.com/nestjs/swagger/pull/853) with a solution but it hasn't been merged yet. Kinda desperate for this since I really want to use nestjs, but if it doesn't work with swagger in combination with azure functions I need to use something else

**Comment by TLaMars** [comment] 2020-09-10 08:30
Hi,
My company is looking for this solution.
Is there any idea when this issue will be fixed? My company really needs a solution, because we use azure functions and nestjs a lot and want to have swagger working in it.

**Comment by jacobdo2** [comment] 2020-09-10 09:42
My *not a solution* was to keep using azure function for calls and deploy the solution for swagger's sake somewhere else.

**Comment by abeebola** [comment] 2020-09-25 08:55
I have this issue too. My workaround for the `swagger-ui-init.js` (using an nginx server) was to add the following directive:

```
location = /swagger/swagger-ui-init.js {
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header Host $http_host;

        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";

        proxy_pass http://api_upstream/swagger/swagger-ui-init.js;
        proxy_redirect off;
        proxy_read_timeout 240s;
}
```

By using this exact match, the request is passed directly to NestJS.
The problem was that nginx was trying to find the file which doesn't actually exist

**Comment by kamilmysliwiec** [comment] 2021-03-19 14:07
This issue should be reported in the `swagger-ui-express` repository.

**Closed by kamilmysliwiec** 2021-03-19 14:07 UTC
Labels: needs triage
