### ISSUE TITLE
SwaggerModule.createDocument crash when controller path is a string Array

### ISSUE THREAD

**Issue by Kennytian** [nestjs/swagger#358] opened 2019-10-13 16:40 UTC
if `path` is a string Array, will make crash.

for example:

@Get(['find-all', 'find_all']) in controller

https://github.com/nestjs/swagger/blob/f8f34afd31c1fae931ddb514389d5d517e0a79f7/lib/swagger-explorer.ts#L176

crash info:

```
(node:31319) UnhandledPromiseRejectionWarning: TypeError: str.substr is not a function
    at Function.parse (/Users/kenny/projects/private/node/hello-nest/node_modules/path-to-regexp/index.js:107:28)
    at SwaggerExplorer.validateRoutePath (/Users/kenny/projects/private/node/hello-nest/node_modules/@nestjs/swagger/dist/swagger-explorer.js:108:45)
    at SwaggerExplorer.exploreRoutePathAndMethod (/Users/kenny/projects/private/node/hello-nest/node_modules/@nestjs/swagger/dist/swagger-explorer.js:93:44)
    at explorers.reduce (/Users/kenny/projects/private/node/hello-nest/node_modules/@nestjs/swagger/dist/swagger-explorer.js:55:45)
    at Array.reduce (<anonymous>)
    at lodash_1.mapValues (/Users/kenny/projects/private/node/hello-nest/node_modules/@nestjs/swagger/dist/swagger-explorer.js:54:97)
    at /Users/kenny/projects/private/node/hello-nest/node_modules/@nestjs/swagger/node_modules/lodash/lodash.js:13401:38
    at /Users/kenny/projects/private/node/hello-nest/node_modules/@nestjs/swagger/node_modules/lodash/lodash.js:4905:15
    at baseForOwn (/Users/kenny/projects/private/node/hello-nest/node_modules/@nestjs/swagger/node_modules/lodash/lodash.js:2990:24)
    at Function.mapValues (/Users/kenny/projects/private/node/hello-nest/node_modules/@nestjs/swagger/node_modules/lodash/lodash.js:13400:7)
    at MapIterator.denormalizedPaths.metadataScanner.scanFromPrototype.name [as iteratee] (/Users/kenny/projects/private/node/hello-nest/node_modules/@nestjs/swagger/dist/swagger-explorer.js:54:45)
    at MapIterator.next (/Users/kenny/projects/private/node/hello-nest/node_modules/iterare/lib/map.js:13:39)
    at FilterIterator.next (/Users/kenny/projects/private/node/hello-nest/node_modules/iterare/lib/filter.js:12:34)
    at IteratorWithOperators.next (/Users/kenny/projects/private/node/hello-nest/node_modules/iterare/lib/iterate.js:21:28)
    at Function.from (<anonymous>)
    at IteratorWithOperators.toArray (/Users/kenny/projects/private/node/hello-nest/node_modules/iterare/lib/iterate.js:180:22)

```

**Comment by kamilmysliwiec** [comment] 2019-12-03 10:44
Duplicate of https://github.com/nestjs/swagger/issues/268

**Closed by kamilmysliwiec** 2019-12-03 10:44 UTC
