### ISSUE TITLE
How to make object query parameters

### ISSUE THREAD

**Issue by bostrom** [nestjs/swagger#90] opened 2018-05-23 10:17 UTC
I'm trying to figure out how to make my ApiModelProperty decorators so that Swagger would work with objects as query parameters. My case is something like this:

```
class PersonQueryDto {
  @ApiModelProperty({
    type: QueryFilterDto,
    isArray: true,
    example: [{ field: 'age', comparator: 'gt', value: 25 }],
  })
  readonly filters: QueryFilterDto[];
}

class QueryFilterDto {
  @ApiModelProperty({
    type: 'string',
  })
  readonly field: string; 

  @ApiModelProperty({
    type: 'string',
  })
  readonly comparator: string; 

  @ApiModelProperty({
    type: 'any',
  })
  readonly value: any; 
}
```

The swagger UI, however, ends up looking like this

![image](https://user-images.githubusercontent.com/430963/40418572-65b019de-5e8b-11e8-97ff-a4c4389482ee.png)

And it doesn't know how to deserialise the object passed.

What's the trick?

**Comment by nursik** [comment] 2018-05-24 12:21
You should pass String instead of 'string' in type property. Also you should define your example in QueryFilterDto like this
`class QueryFilterDto {
  @ApiModelProperty({
    type: String,
    example: 'age',
  })
  readonly field: string; 

  @ApiModelProperty({
    type: String,
    example: 'gt',
  })
  readonly comparator: string; 

  @ApiModelProperty({
    type: Object,
    example: 25,
  })
  readonly value: any; 
}
`

**Comment by bostrom** [comment] 2018-05-24 13:37
Thanks @nursik. So I changed the things you mentioned, but Swagger don't seem to be able to serialise the parameters into a query string. The resulting URL is

`query?size=10&start=0&filters=%5Bobject%20Object%5D`

i.e. the filters is just seen as an "[object Object]". 

The problem isn't the QueryFilterDto since it contains only primitives, but the PersonQueryDto that contains a reference to a complex object.

**Comment by nursik** [comment] 2018-05-29 21:35
@bostrom Actually the problem is disambiguation. How we can get query as array of objects? I think you should reconsider your query for filters parameter, because there are many different ways to pass array of objects.

Also I suggest to have filters query accept array of strings rather than array of objects. So you can send like this: `query?filters=age,gt,25&filters=age,lt,30`. So your QueryFilterDTO object is created from string. `Transform` decorator from class-transformer can help you.

**Comment by bostrom** [comment] 2018-05-31 08:50
@nursik Yes, having query params encoded as comma delimited strings would work. And actually that's what I'm aiming at. 

The interpretation of the query string in the backend is not my problem, the problem is entering the query parameters using Swagger UI in a way that Swagger UI would allow me to input the parameters in some form fields and it would encode the parameters according to some settings as explained here https://swagger.io/docs/specification/serialization/

The problem is that I don't seem to be able to configure Swagger properly through the ApiModelProperty. I.e. how do I tell Swagger what type of data the query parameters expect and how to encode them on the URL? 

The only way I could solve this is to use POST and send the query object in the body.

**Comment by Pietrox** [comment] 2019-06-05 12:14
@bostrom Any luck with figuring it out?
I stumbled on the same issue, not only example (using default atm) is not deserialized, but also nested object is not being generated as ready inputs.

**Comment by bostrom** [comment] 2019-06-05 13:07
@Pietrox it's been a while but IIRC I never got this to work properly.

**Comment by jmls** [comment] 2019-06-19 20:26
I've hit this as well - anyone got any idea on how to generate a model / class / interface that could be passed as a query parameter for swagger to visualize ?

**Comment by MightyNox** [comment] 2020-05-12 11:02
Same problem here. I have to pass objects in query as polymorphic array.
Example from docs:
```
@ApiProperty({
  type: 'array',
  items: {
    oneOf: [
      { $ref: getSchemaPath(Cat) },
      { $ref: getSchemaPath(Dog) },
    ],
  },
})
pets: Pet[];
```

Unfortunatelly when I'm using @Query() decorator in my controller, swagger-ui cannot display given endpoint.

**Comment by jmls** [comment] 2020-09-17 10:12
gah. still an issue :(

**Comment by nartc** [comment] 2020-11-14 05:00
OpenAPI 3.0 spec does not allow for nested `query`. If you want to annotate a query with a key of `filters` that is an array, use `ApiQuery`
![image](https://user-images.githubusercontent.com/25516557/99140084-ef828d80-2603-11eb-9d53-05d073a9d57f.png)

here's the output:
![image](https://user-images.githubusercontent.com/25516557/99140085-f3161480-2603-11eb-88a1-6285a5b2e0ec.png)

Closing.

**Closed by nartc** 2020-11-14 05:00 UTC
Labels: potential issue

**Comment by MarZab** [comment] 2021-03-26 17:10
Highjacking this thread since this it helped me figure out how to do a similar task with a simple object with full Swagger support:

Example: `?filters[name]=Marko&filters[age]=21`

```
    ApiExtraModels(QueryFilterDto),
    ApiQuery({
      required: false,
      name: 'filters',
      style: 'deepObject',
      explode: true,
      type: 'object',
      schema: {
        $ref: getSchemaPath(QueryFilterDto),
      },
    }),
```

Full example here: https://gist.github.com/MarZab/c6311f83dec6401966e847c55d81a9bb

**Comment by maxvashchuk** [comment] 2021-05-19 08:22
You can do something like this:

```
export class OrderDto {
	@IsEnum(SORT)
	@IsOptional()
	@Expose()
	@ApiPropertyOptional({enum: SORT, name: 'orderBy[createdAt]'})
	createdAt?:  @SORT;

	@IsEnum(SORT)
	@IsOptional()
	@Expose()
	@ApiPropertyOptional({enum: SORT, name: 'orderBy[updatedAt]'})
	updatedAt?: SORT;

	@IsEnum(SORT)
	@IsOptional()
	@Expose()
	@ApiPropertyOptional({enum: SORT, name: 'orderBy[name]'})
	name?: SORT;
}

export class CollectionDto  {
        // ......

	@ValidateNested()
	@IsOptional()
	@ApiPropertyOptional({type: () => OrderDto})
	@Type(() => OrderDto)
	@Expose()
	orderBy?: OrderDto;
}
```

![example](https://user-images.githubusercontent.com/5963566/118780243-84589300-b894-11eb-8463-b4634c7a40bb.png)

**Comment by codr1** [comment] 2022-05-09 15:27
Hi, all.  This is a bit of a long running thread but I am running into a similar issue.  

Here is a dto that I built
![image](https://user-images.githubusercontent.com/7825101/167442329-6554a834-1b4a-4554-a0dc-14b5c19f7dda.png)

It is included in ApiExtraModels
![image](https://user-images.githubusercontent.com/7825101/167442537-c4815a60-14c6-481c-9a64-e6f727bfc125.png)

Then I add it as an ApiQuery
![image](https://user-images.githubusercontent.com/7825101/167442686-2dbeffe1-6665-4547-ab63-0e1eb980d2e5.png)

But all I see in the swagger is a generic object.
![image](https://user-images.githubusercontent.com/7825101/167443533-7d4014b7-92e4-4cc3-8aec-78dee764c505.png)

I do see the model 
![image](https://user-images.githubusercontent.com/7825101/167443693-8b5c102a-61e9-43fc-be0a-1b6ed9f39d61.png)


But for whatever reason - I don't see it in the swagger of the function.  It just shows object
