### ISSUE TITLE
Modification not effective when using start:dev

### ISSUE THREAD

**Issue by zstiu** [nestjs/swagger#760] opened 2020-05-20 03:14 UTC
## Current behavior
I'm using start:dev in my development env. But sometimes, I found my modification not effective, until I close it and run ```npm run build``` and restart it.
Sorry for that I have no time to see which modifications can cause the problem.But always found this happens when I'm editing my Entity code(typeorm), after editing the code, swagger docs not change, but after ```npm run build``` ```npm run start:dev``` ,the docs changed.

## Input Code
For example:
Entity like this:
```ts
...
  password!: string
...
```
swagger will show the password, but I don't want this.
so I add this in my Entity
```ts
...
  @ApiHideProperty()
  password!: string
...
```
but swagger doc still display the password.
then I run ```npm run build``` ```npm run start:dev``` 
the swagger show the correct docs

## Environment

<pre><code>
Nest version: @nestjs/common@7.0.9
Swagger version: @nestjs/swagger@4.5.5

 
For Tooling issues:
- Node version: 12.16.2
- Platform:  Mac os

Others:

**Comment by zstiu** [comment] 2020-05-20 06:40
@jmcdo29 coming soon after work.

**Comment by zstiu** [comment] 2020-05-20 14:03
@jmcdo29 
Hi, here reproduce this issue.
[https://github.com/zstiu/nestDemo](https://github.com/zstiu/nestDemo)
the file path in [here](https://github.com/zstiu/nestDemo/blob/master/src/entities/user/user.entity.ts)

I try to comment the line ```@ApiHideProperty()```, to reproduce it,
but the first few times I comment the code the swagger docs display normal.

Then I can see this issue after comment ```@ApiHideProperty()``` on and off several times.

**Comment by Vandell63** [comment] 2020-05-22 13:35
Hi there, i was just going to open an issue on it !!
I got the same issue here. I can explain a bit more.
As soon as you used the `start:dev` nest will compile on fly on every change. BUT in your tsconfig it recompile in a `incremental` way so your change will reflect as it goes in his compilation ( don't know yet if it come from the incremental option in tsconfig ).

To be simple:
The use case is the following:
- My entity is empty without any `ApiProperty` decorator
- I add an `ApiProperty` decorator on a class property
- Change detected -> Recompile
- In Swagger ui i can see the new property added
------- Now
- I made a mistake,  i remove the `ApiProperty` OR i replace by `ApiHideProperty` decorator
- Change detected -> Recompile
- !! Nothing has change, i always got this property in my swagger ui

So if you **remove** the dist file, then build your app manually and run `start` ( node dist/main.js ) then you will have your swagger ui properly done ( and in this example the property is now hidden properly ) as @zstiu said.

I have investigate more and i encounter other issue like:
- When you start (dev) for the first time swagger it success to parse some of entities but not all of them sometimes.
- If you edit one of them it, swagger success finally to get the entity property after the re-compilation.

Voilà, hope it can be more clear and resolve this issue.

**Comment by jmcdo29** [comment] 2020-05-22 23:35
@zstiu in your reproduction, would you either add a `docker-compose` for the database or remove the dependency on it completely?

**Comment by zstiu** [comment] 2020-05-25 04:10
@jmcdo29 Done it.

**Comment by jmcdo29** [comment] 2020-05-25 06:04
Okay, I see it happening, but I can't say why, because the decorator code properly changes between compilations. Seems like an issue possible with `swagger-express-ui` instead of `@nestjs/swagger`

**Comment by dsbert** [comment] 2020-05-27 18:10
I am also running into this issue. Running `npm start:dev` again does not update the docs fully, but manually performing an `npm build` does.

**Comment by kamilmysliwiec** [comment] 2020-08-20 11:00
It should be fixed now (4.6.0)

**Closed by kamilmysliwiec** 2020-08-20 11:00 UTC
Labels: needs clarification

**Comment by crscnc** [comment] 2024-08-22 01:37
Still not working!

**Comment by PatrykKuniczak** [comment] 2024-08-22 06:35
@kamilmysliwiec That's a years with this bug, maybe we can bake a cake 😆
