### ISSUE TITLE
Required meta is hardcoded to true when implicit  params mapping to meta rather evaluating it to param.isOptional() 

### ISSUE THREAD

**Issue by rsirs** [nestjs/swagger#177] opened 2018-12-28 17:03 UTC
https://github.com/nestjs/swagger/blob/79fa84a2444997419022ea9b27154c856827a044/lib/explorers/api-parameters.explorer.ts#L83

For example:
```ts
create(@Body() body: ReqBody, @Query('xyz') xyz?: ReqQueryParam) {
}
```
Here query param XYZ is interpreted as required even though it is optional param because of hardcoded ``` required=true```. Now, To make it optional we have to explicitly define 
```ts
@ApiImplicitQuery({
    name: 'xyz',
    required: false,
  })
create(@Body() body: ReqBody, @Query('xyz') xyz?: ReqQueryParam) {
}
```
if we make this something like ```required=!isOptional(param)``` we don't need to add addition ```ApiImplicitQuery``` annotation for required field.

Any thought on that?

**Comment by kamilmysliwiec** [comment] 2019-02-01 12:33
Duplicate of #30

**Closed by kamilmysliwiec** 2019-02-01 12:33 UTC
