### ISSUE TITLE
@nestjs/swagger/plugin requires at least one decorator in the class to generate ApiProperty automatically

### ISSUE THREAD

**Issue by dngconsulting** [nestjs/swagger#413] opened 2019-12-04 14:31 UTC
## Current behavior
Swagger module need at least one decorator in a class to correctly decorate classes with @nestjs/swagger/plugin

## Step to reproduce 
Take the default E2E sample (cats) provided in @nestjs/swagger/plugin. Remove all class-validator decorators. 

```
export class CreateCatDto {
  readonly name: string;

  readonly age: number;

  readonly breed: string;
}

```

## Expected behavior
Should add ApiProperty automatically to all fields.
**When no decorator is provided at all NestJS doesn't decorate the class.**

## Possible Solution/Workaround
Add one fake decorator on any field :-)

## Environment
Nest version: 6.10.5
"nestjs/swagger": "4.0.2",
 
For Tooling issues:
- Node version: latest
- Platform:  Windows

An issue in model-class.visitor.ts visit() method ?

**Comment by kamilmysliwiec** [comment] 2019-12-05 07:36
Please, provide a minimal repository which reproduces your issue.

**Comment by kamilmysliwiec** [comment] 2019-12-05 08:01
Fixed in 4.0.6 :)

**Closed by kamilmysliwiec** 2019-12-05 08:01 UTC
Labels: needs clarification

**Comment by dngconsulting** [comment] 2019-12-05 08:19
You rock Kamil :-)

**Comment by cjancsar** [comment] 2019-12-17 05:36
@kamilmysliwiec I am on `"version": "4.0.9",` and this still seems to be an issue. Is there a link to the commit and regression tests that resolved this?

**Comment by dngconsulting** [comment] 2019-12-17 07:58
`4.0.9` is fine for me after updating. Have to tried to remove cache, node_modules, ... ?

**Comment by muke1908** [comment] 2020-03-13 15:07
Using `@nestjs/swagger:^4.3.2`, still facing the issue.

**Comment by joshstrange** [comment] 2020-05-18 20:31
Using `@nestjs/swagger: 4.5.7`, same issue, thankfully just throwing a single `@ApiProperty` on any field for my entity let it generate the types for all other properties. My entities were not picked up even with the proper suffix. If you have in-line DTO's then they only way forward is to put `@ApiProperty` on all the properties OR move them into `.dto.ts` files. I think you still have to put at least 1 `@ApiProperty` on it but I think any `class-validator`'s will cause it to be picked up. Which makes sense as I don't use any `class-validator` annotations on my actual entities (models). It needs at least something in the file to pick up it appears.

**Comment by kamilmysliwiec** [comment] 2020-05-19 07:56
Please, create a separate issue with a reproduction repository linked.
