### ISSUE TITLE
Documentation - Schema generation from DTO

### ISSUE THREAD

**Issue by VladimirAkopyan** [nestjs/swagger#394] opened 2019-11-30 03:22 UTC
I have DTOs specified with [Class-Validator][1] and I am looking  to produce Swagger definitions without a NestJS Server.
Ideally I would like to pass in a DTO definition and get it's Swagger schema. 

I have been reading the source, but am struggling to understand which function in the framework actually does that. At best, I have been able to track it down to [`modelsDefinitions` property in `swagger-explorer` class][3]. 

As best I can tell, from there it explores controllers used by NestJS, and this is done by: [`api-parameters.explorer`][4] and [`api-produces.explorer`][5]. The way they work is not clear to me. I was wondering of someone might help me out? 

  [1]: https://github.com/typestack/class-validator
  [2]: https://github.com/nestjs/swagger
  [3]: https://github.com/nestjs/swagger/blob/master/lib/swagger-explorer.ts
  [4]: https://github.com/nestjs/swagger/blob/master/lib/explorers/api-parameters.explorer.ts
  [5]: https://github.com/nestjs/swagger/blob/master/lib/explorers/api-produces.explorer.ts

**Comment by kamilmysliwiec** [comment] 2019-12-03 10:30
Duplicate of https://github.com/nestjs/swagger/issues/231

**Closed by kamilmysliwiec** 2019-12-03 10:30 UTC

**Comment by VladimirAkopyan** [comment] 2019-12-03 10:39
It is not a duplicate, i am not asking anyone to build a CLI.
I am asking for documentation, on which function translates a DTOs to Swagger data models, if there is a singular function.

**Comment by kamilmysliwiec** [comment] 2019-12-03 10:43
My mistake. 

All factories take as input parameters metadata objects (merged class metadata & context metadata) so it won't be that easy (but it's definitely feasible)
