### ISSUE TITLE
ApiQuery issue when using "content"

### ISSUE THREAD

**Issue by jjescof** [nestjs/swagger#2638] opened 2023-09-28 19:21 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

I was trying to use a Query parameter as a JSON object, so in order to describe it and support "nested objects or arrays" the official Open API documentation suggests using "content" instead of "schema" https://swagger.io/docs/specification/describing-parameters/#schema-vs-content

Now going to the NestJS Implementation, I use:
```
@ApiQuery({
      required: false,
      name: 'filter',
      description: 'Filter Query object',
      content: {
        'application/json': {
          schema: {
            format: 'json',
            type: 'object',
            items: {
              oneOf: [...],
            },
          },
          example: {
            name: { begins: 'gen' },
            createdAt: { gt: '2023-09-28T15:41:45.779Z' } },
        },
      },
    })
```

Everything goes well and it works as expected on Swagger Explorer serves by my NestJS application.

The problem arises when I take the JSON from https://localhost:3000/api-json to check the file in online tools like
https://editor.swagger.io/ or when I use the same file for openapi generation tool openapi-generator-cli.

Those tools report an error regarding the generated JSON file from NestJS, it is that content and schema should be mutually  exclusive, but NestJS adds an empty schema Object in the definition:

![image](https://github.com/nestjs/swagger/assets/9410631/d94ce220-a32d-4dc1-8a99-b572933a3abe)

As shown in the first snippet code, there is no schema in the ApiQuery Options, instead, content is added, but at generation time an empty schema is added.

I would like to help to solve this error but I'm not sure where to start checking for this, so any advice will be really appreciated.

### Minimum reproduction code

-

### Steps to reproduce

Add a ApiQuery decorator add Method level with content field instead of schema.

### Expected behavior

When **content** is added to ApiQuery decorator it shouldn't add an empty schema object

### Package version

7.1.12

### NestJS version

9.1.1

### Node.js version

18.15.0

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by kamilmysliwiec** [comment] 2023-09-29 07:06
Would you like to create a PR for this issue?

**Comment by jjescof** [comment] 2023-09-29 16:44
I would like to create a PR but I don't understand where this tag is being written to the document, can you give me some insights, please?

**Comment by alenap93** [comment] 2024-01-13 17:10
@jjescof the point is:
```diff
  private readonly metadataScanner = new MetadataScanner();
+ private readonly schemas?: Record<string, SchemaObject>;
- private readonly schemas: Record<string, SchemaObject> = {};
  private operationIdFactory: OperationIdFactory = (
```
but this fix create too many problems, why the schemas empty object gives you problem?

**Comment by clintonb** [comment] 2024-01-27 16:41
This is a duplicate of https://github.com/nestjs/swagger/issues/1461.

**Closed** 2024-01-29 08:13 UTC
Labels: bug, needs triage
