### ISSUE TITLE
Defining ApiResponse at controller level doesnt work properly

### ISSUE THREAD

**Issue by ToKaTpoHb** [nestjs/swagger#48] opened 2018-02-06 19:47 UTC
For example, i have UsersController:
```
@ApiUseTags('users')
@ApiResponse({ status: 403, description: 'Forbidden. Please provide valid bearer token.' })
@Controller('users')
export default class UsersController {
...
  @Get()
  async getAllUsers() {
  ...
  @ApiOperation({ title: 'Create new user' })
  @ApiResponse({ status: 200, description: 'User has been successfully created.', type: CreateUserResponce })
  @ApiResponse({ status: 400, description: 'Request did not passed validation.' })
  @Post()
  @UsePipes(new ValidationPipe())
  async createUser(@Body() user: CreateUserDto): Promise<CreateUserResponce> {
  ...
```

In the swagger ui i have this:
![image](https://user-images.githubusercontent.com/11059471/35880318-480f9b50-0b86-11e8-8627-084117437f47.png)
Now we see, that if i don't define `@ApiResponse` for method, like in `getAllUsers`everything works as expected, but if i define `@ApiResponse` at least once, controller-defined `@ApiResponse` getting overridden.

**Comment by thohoh** [comment] 2018-02-07 14:05
The same question. Please give us some info on that. @kamilmysliwiec @alisherks

**Comment by ToKaTpoHb** [comment] 2018-02-07 18:42
By the way, im using swagger v1.1.4.

**Comment by thohoh** [comment] 2018-02-09 14:41
@kamilmysliwiec So is it a bug or misuse?

**Comment by fwoelffel** [comment] 2018-02-09 17:32
Duplicate of https://github.com/nestjs/swagger/issues/36

**Comment by kamilmysliwiec** [comment] 2018-03-30 11:13
Duplicate #36 (fixed)

**Closed by kamilmysliwiec** 2018-03-30 11:13 UTC
